/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Administrative content source list.
 */
export const AdminContentSourcesListQueryParams = zod.strictObject({
  platform: zod
    .enum(['telegram', 'dzen', 'instagram', 'tiktok', 'vk', 'pinterest'])
    .optional(),
  status: zod.enum(['active', 'disabled']).optional(),
})

export const AdminContentSourcesList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      channelId: zod.string().nullable(),
      createdAt: zod.iso.datetime({ offset: true }),
      displayName: zod.string(),
      externalId: zod.string().nullable(),
      handle: zod.string().nullable(),
      id: zod.string(),
      lastCursor: zod.string().nullable(),
      lastImportedAt: zod.iso.datetime({ offset: true }).nullable(),
      platform: zod.enum([
        'telegram',
        'dzen',
        'instagram',
        'tiktok',
        'vk',
        'pinterest',
      ]),
      status: zod.enum(['active', 'disabled']),
      updatedAt: zod.iso.datetime({ offset: true }),
      url: zod.url(),
    }),
  ),
})

export const adminContentSourcesList401ResponseStatusMin = 400
export const adminContentSourcesList401ResponseStatusMax = 599

export const AdminContentSourcesList401Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesList401ResponseStatusMin)
    .max(adminContentSourcesList401ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesList403ResponseStatusMin = 400
export const adminContentSourcesList403ResponseStatusMax = 599

export const AdminContentSourcesList403Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesList403ResponseStatusMin)
    .max(adminContentSourcesList403ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesList422ResponseErrorsItemCodeRegExp =
  new RegExp('^[a-z][a-z0-9_]*$')
export const adminContentSourcesList422ResponseErrorsItemPointerRegExp =
  new RegExp('^(?:|/(?:[^~/]|~0|~1)*)$')
export const adminContentSourcesList422ResponseStatusMin = 400
export const adminContentSourcesList422ResponseStatusMax = 599

export const AdminContentSourcesList422Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  errors: zod.array(
    zod.strictObject({
      code: zod
        .string()
        .regex(adminContentSourcesList422ResponseErrorsItemCodeRegExp),
      detail: zod.string(),
      pointer: zod
        .string()
        .regex(adminContentSourcesList422ResponseErrorsItemPointerRegExp),
    }),
  ),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesList422ResponseStatusMin)
    .max(adminContentSourcesList422ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesList500ResponseStatusMin = 400
export const adminContentSourcesList500ResponseStatusMax = 599

export const AdminContentSourcesList500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesList500ResponseStatusMin)
    .max(adminContentSourcesList500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Created content source.
 */

export const AdminContentSourcesCreateBody = zod.strictObject({
  channelId: zod.string().min(1).nullish(),
  displayName: zod.string().min(1),
  externalId: zod.string().min(1).nullish(),
  handle: zod.string().min(1).nullish(),
  platform: zod.enum([
    'telegram',
    'dzen',
    'instagram',
    'tiktok',
    'vk',
    'pinterest',
  ]),
  url: zod.url(),
})

export const AdminContentSourcesCreate201Response = zod.strictObject({
  channelId: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  displayName: zod.string(),
  externalId: zod.string().nullable(),
  handle: zod.string().nullable(),
  id: zod.string(),
  lastCursor: zod.string().nullable(),
  lastImportedAt: zod.iso.datetime({ offset: true }).nullable(),
  platform: zod.enum([
    'telegram',
    'dzen',
    'instagram',
    'tiktok',
    'vk',
    'pinterest',
  ]),
  status: zod.enum(['active', 'disabled']),
  updatedAt: zod.iso.datetime({ offset: true }),
  url: zod.url(),
})

export const adminContentSourcesCreate400ResponseStatusMin = 400
export const adminContentSourcesCreate400ResponseStatusMax = 599

export const AdminContentSourcesCreate400Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesCreate400ResponseStatusMin)
    .max(adminContentSourcesCreate400ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesCreate401ResponseStatusMin = 400
export const adminContentSourcesCreate401ResponseStatusMax = 599

export const AdminContentSourcesCreate401Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesCreate401ResponseStatusMin)
    .max(adminContentSourcesCreate401ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesCreate403ResponseStatusMin = 400
export const adminContentSourcesCreate403ResponseStatusMax = 599

export const AdminContentSourcesCreate403Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesCreate403ResponseStatusMin)
    .max(adminContentSourcesCreate403ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesCreate409ResponseStatusMin = 400
export const adminContentSourcesCreate409ResponseStatusMax = 599

export const AdminContentSourcesCreate409Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesCreate409ResponseStatusMin)
    .max(adminContentSourcesCreate409ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesCreate422ResponseErrorsItemCodeRegExp =
  new RegExp('^[a-z][a-z0-9_]*$')
export const adminContentSourcesCreate422ResponseErrorsItemPointerRegExp =
  new RegExp('^(?:|/(?:[^~/]|~0|~1)*)$')
export const adminContentSourcesCreate422ResponseStatusMin = 400
export const adminContentSourcesCreate422ResponseStatusMax = 599

export const AdminContentSourcesCreate422Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  errors: zod.array(
    zod.strictObject({
      code: zod
        .string()
        .regex(adminContentSourcesCreate422ResponseErrorsItemCodeRegExp),
      detail: zod.string(),
      pointer: zod
        .string()
        .regex(adminContentSourcesCreate422ResponseErrorsItemPointerRegExp),
    }),
  ),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesCreate422ResponseStatusMin)
    .max(adminContentSourcesCreate422ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesCreate500ResponseStatusMin = 400
export const adminContentSourcesCreate500ResponseStatusMax = 599

export const AdminContentSourcesCreate500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesCreate500ResponseStatusMin)
    .max(adminContentSourcesCreate500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Updated content source.
 */
export const AdminContentSourcesUpdateParams = zod.strictObject({
  sourceId: zod.string(),
})

export const AdminContentSourcesUpdateBody = zod.strictObject({
  channelId: zod.string().min(1).nullish(),
  displayName: zod.string().min(1).optional(),
  externalId: zod.string().min(1).nullish(),
  handle: zod.string().min(1).nullish(),
  url: zod.url().optional(),
})

export const AdminContentSourcesUpdate200Response = zod.strictObject({
  channelId: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  displayName: zod.string(),
  externalId: zod.string().nullable(),
  handle: zod.string().nullable(),
  id: zod.string(),
  lastCursor: zod.string().nullable(),
  lastImportedAt: zod.iso.datetime({ offset: true }).nullable(),
  platform: zod.enum([
    'telegram',
    'dzen',
    'instagram',
    'tiktok',
    'vk',
    'pinterest',
  ]),
  status: zod.enum(['active', 'disabled']),
  updatedAt: zod.iso.datetime({ offset: true }),
  url: zod.url(),
})

export const adminContentSourcesUpdate400ResponseStatusMin = 400
export const adminContentSourcesUpdate400ResponseStatusMax = 599

export const AdminContentSourcesUpdate400Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdate400ResponseStatusMin)
    .max(adminContentSourcesUpdate400ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesUpdate401ResponseStatusMin = 400
export const adminContentSourcesUpdate401ResponseStatusMax = 599

export const AdminContentSourcesUpdate401Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdate401ResponseStatusMin)
    .max(adminContentSourcesUpdate401ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesUpdate403ResponseStatusMin = 400
export const adminContentSourcesUpdate403ResponseStatusMax = 599

export const AdminContentSourcesUpdate403Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdate403ResponseStatusMin)
    .max(adminContentSourcesUpdate403ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesUpdate404ResponseStatusMin = 400
export const adminContentSourcesUpdate404ResponseStatusMax = 599

export const AdminContentSourcesUpdate404Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdate404ResponseStatusMin)
    .max(adminContentSourcesUpdate404ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesUpdate409ResponseStatusMin = 400
export const adminContentSourcesUpdate409ResponseStatusMax = 599

export const AdminContentSourcesUpdate409Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdate409ResponseStatusMin)
    .max(adminContentSourcesUpdate409ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesUpdate422ResponseErrorsItemCodeRegExp =
  new RegExp('^[a-z][a-z0-9_]*$')
export const adminContentSourcesUpdate422ResponseErrorsItemPointerRegExp =
  new RegExp('^(?:|/(?:[^~/]|~0|~1)*)$')
export const adminContentSourcesUpdate422ResponseStatusMin = 400
export const adminContentSourcesUpdate422ResponseStatusMax = 599

export const AdminContentSourcesUpdate422Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  errors: zod.array(
    zod.strictObject({
      code: zod
        .string()
        .regex(adminContentSourcesUpdate422ResponseErrorsItemCodeRegExp),
      detail: zod.string(),
      pointer: zod
        .string()
        .regex(adminContentSourcesUpdate422ResponseErrorsItemPointerRegExp),
    }),
  ),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdate422ResponseStatusMin)
    .max(adminContentSourcesUpdate422ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesUpdate500ResponseStatusMin = 400
export const adminContentSourcesUpdate500ResponseStatusMax = 599

export const AdminContentSourcesUpdate500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdate500ResponseStatusMin)
    .max(adminContentSourcesUpdate500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Queued Telegram import run.
 */
export const AdminTelegramImportsEnqueueParams = zod.strictObject({
  sourceId: zod.string(),
})

export const adminTelegramImportsEnqueueQueryLimitDefault = 50
export const adminTelegramImportsEnqueueQueryLimitMax = 100

export const AdminTelegramImportsEnqueueQueryParams = zod.strictObject({
  limit: zod
    .int()
    .min(1)
    .max(adminTelegramImportsEnqueueQueryLimitMax)
    .default(adminTelegramImportsEnqueueQueryLimitDefault),
})

export const adminTelegramImportsEnqueue201ResponseCreatedCountMin = 0

export const adminTelegramImportsEnqueue201ResponseFoundCountMin = 0

export const adminTelegramImportsEnqueue201ResponseSkippedDuplicateCountMin = 0

export const adminTelegramImportsEnqueue201ResponseUpdatedCountMin = 0

export const AdminTelegramImportsEnqueue201Response = zod.strictObject({
  createdAt: zod.iso.datetime({ offset: true }),
  createdCount: zod
    .number()
    .min(adminTelegramImportsEnqueue201ResponseCreatedCountMin),
  errorMessage: zod.string().nullable(),
  finishedAt: zod.iso.datetime({ offset: true }).nullable(),
  foundCount: zod
    .number()
    .min(adminTelegramImportsEnqueue201ResponseFoundCountMin),
  id: zod.string(),
  skippedDuplicateCount: zod
    .number()
    .min(adminTelegramImportsEnqueue201ResponseSkippedDuplicateCountMin),
  sourceId: zod.string(),
  startedAt: zod.iso.datetime({ offset: true }).nullable(),
  status: zod.enum(['queued', 'running', 'completed', 'failed']),
  updatedAt: zod.iso.datetime({ offset: true }),
  updatedCount: zod
    .number()
    .min(adminTelegramImportsEnqueue201ResponseUpdatedCountMin),
})

export const adminTelegramImportsEnqueue400ResponseStatusMin = 400
export const adminTelegramImportsEnqueue400ResponseStatusMax = 599

export const AdminTelegramImportsEnqueue400Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminTelegramImportsEnqueue400ResponseStatusMin)
    .max(adminTelegramImportsEnqueue400ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminTelegramImportsEnqueue401ResponseStatusMin = 400
export const adminTelegramImportsEnqueue401ResponseStatusMax = 599

export const AdminTelegramImportsEnqueue401Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminTelegramImportsEnqueue401ResponseStatusMin)
    .max(adminTelegramImportsEnqueue401ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminTelegramImportsEnqueue403ResponseStatusMin = 400
export const adminTelegramImportsEnqueue403ResponseStatusMax = 599

export const AdminTelegramImportsEnqueue403Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminTelegramImportsEnqueue403ResponseStatusMin)
    .max(adminTelegramImportsEnqueue403ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminTelegramImportsEnqueue404ResponseStatusMin = 400
export const adminTelegramImportsEnqueue404ResponseStatusMax = 599

export const AdminTelegramImportsEnqueue404Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminTelegramImportsEnqueue404ResponseStatusMin)
    .max(adminTelegramImportsEnqueue404ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminTelegramImportsEnqueue409ResponseStatusMin = 400
export const adminTelegramImportsEnqueue409ResponseStatusMax = 599

export const AdminTelegramImportsEnqueue409Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminTelegramImportsEnqueue409ResponseStatusMin)
    .max(adminTelegramImportsEnqueue409ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminTelegramImportsEnqueue422ResponseErrorsItemCodeRegExp =
  new RegExp('^[a-z][a-z0-9_]*$')
export const adminTelegramImportsEnqueue422ResponseErrorsItemPointerRegExp =
  new RegExp('^(?:|/(?:[^~/]|~0|~1)*)$')
export const adminTelegramImportsEnqueue422ResponseStatusMin = 400
export const adminTelegramImportsEnqueue422ResponseStatusMax = 599

export const AdminTelegramImportsEnqueue422Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  errors: zod.array(
    zod.strictObject({
      code: zod
        .string()
        .regex(adminTelegramImportsEnqueue422ResponseErrorsItemCodeRegExp),
      detail: zod.string(),
      pointer: zod
        .string()
        .regex(adminTelegramImportsEnqueue422ResponseErrorsItemPointerRegExp),
    }),
  ),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminTelegramImportsEnqueue422ResponseStatusMin)
    .max(adminTelegramImportsEnqueue422ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminTelegramImportsEnqueue500ResponseStatusMin = 400
export const adminTelegramImportsEnqueue500ResponseStatusMax = 599

export const AdminTelegramImportsEnqueue500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminTelegramImportsEnqueue500ResponseStatusMin)
    .max(adminTelegramImportsEnqueue500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminTelegramImportsEnqueue503ResponseStatusMin = 400
export const adminTelegramImportsEnqueue503ResponseStatusMax = 599

export const AdminTelegramImportsEnqueue503Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminTelegramImportsEnqueue503ResponseStatusMin)
    .max(adminTelegramImportsEnqueue503ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Content source with updated status.
 */
export const AdminContentSourcesUpdateStatusParams = zod.strictObject({
  sourceId: zod.string(),
})

export const AdminContentSourcesUpdateStatusBody = zod.strictObject({
  status: zod.enum(['active', 'disabled']),
})

export const AdminContentSourcesUpdateStatus200Response = zod.strictObject({
  channelId: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  displayName: zod.string(),
  externalId: zod.string().nullable(),
  handle: zod.string().nullable(),
  id: zod.string(),
  lastCursor: zod.string().nullable(),
  lastImportedAt: zod.iso.datetime({ offset: true }).nullable(),
  platform: zod.enum([
    'telegram',
    'dzen',
    'instagram',
    'tiktok',
    'vk',
    'pinterest',
  ]),
  status: zod.enum(['active', 'disabled']),
  updatedAt: zod.iso.datetime({ offset: true }),
  url: zod.url(),
})

export const adminContentSourcesUpdateStatus400ResponseStatusMin = 400
export const adminContentSourcesUpdateStatus400ResponseStatusMax = 599

export const AdminContentSourcesUpdateStatus400Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdateStatus400ResponseStatusMin)
    .max(adminContentSourcesUpdateStatus400ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesUpdateStatus401ResponseStatusMin = 400
export const adminContentSourcesUpdateStatus401ResponseStatusMax = 599

export const AdminContentSourcesUpdateStatus401Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdateStatus401ResponseStatusMin)
    .max(adminContentSourcesUpdateStatus401ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesUpdateStatus403ResponseStatusMin = 400
export const adminContentSourcesUpdateStatus403ResponseStatusMax = 599

export const AdminContentSourcesUpdateStatus403Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdateStatus403ResponseStatusMin)
    .max(adminContentSourcesUpdateStatus403ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesUpdateStatus404ResponseStatusMin = 400
export const adminContentSourcesUpdateStatus404ResponseStatusMax = 599

export const AdminContentSourcesUpdateStatus404Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdateStatus404ResponseStatusMin)
    .max(adminContentSourcesUpdateStatus404ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesUpdateStatus422ResponseErrorsItemCodeRegExp =
  new RegExp('^[a-z][a-z0-9_]*$')
export const adminContentSourcesUpdateStatus422ResponseErrorsItemPointerRegExp =
  new RegExp('^(?:|/(?:[^~/]|~0|~1)*)$')
export const adminContentSourcesUpdateStatus422ResponseStatusMin = 400
export const adminContentSourcesUpdateStatus422ResponseStatusMax = 599

export const AdminContentSourcesUpdateStatus422Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  errors: zod.array(
    zod.strictObject({
      code: zod
        .string()
        .regex(adminContentSourcesUpdateStatus422ResponseErrorsItemCodeRegExp),
      detail: zod.string(),
      pointer: zod
        .string()
        .regex(
          adminContentSourcesUpdateStatus422ResponseErrorsItemPointerRegExp,
        ),
    }),
  ),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdateStatus422ResponseStatusMin)
    .max(adminContentSourcesUpdateStatus422ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminContentSourcesUpdateStatus500ResponseStatusMin = 400
export const adminContentSourcesUpdateStatus500ResponseStatusMax = 599

export const AdminContentSourcesUpdateStatus500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminContentSourcesUpdateStatus500ResponseStatusMin)
    .max(adminContentSourcesUpdateStatus500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})
