/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Public collection list.
 */

export const CollectionsList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      coverImageUrl: zod.string().nullable(),
      description: zod.string().nullable(),
      id: zod.string(),
      placeCount: zod.number().min(1),
      slug: zod.string(),
      title: zod.string(),
    }),
  ),
})

export const collectionsList500ResponseStatusMin = 400
export const collectionsList500ResponseStatusMax = 599

export const CollectionsList500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(collectionsList500ResponseStatusMin)
    .max(collectionsList500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Public collection detail.
 */
export const CollectionsGetParams = zod.strictObject({
  collectionSlug: zod.string(),
})

export const collectionsGetQueryPageSizeDefault = 20
export const collectionsGetQueryPageSizeMax = 100

export const collectionsGetQueryPageDefault = 1
export const collectionsGetQueryPageMax = 1000

export const CollectionsGetQueryParams = zod.strictObject({
  pageSize: zod
    .int()
    .min(1)
    .max(collectionsGetQueryPageSizeMax)
    .default(collectionsGetQueryPageSizeDefault),
  page: zod
    .int()
    .min(1)
    .max(collectionsGetQueryPageMax)
    .default(collectionsGetQueryPageDefault),
})

export const collectionsGet200ResponseItemsItemCountersDzenMin = 0

export const collectionsGet200ResponseItemsItemCountersInstagramMin = 0

export const collectionsGet200ResponseItemsItemCountersTelegramMin = 0

export const collectionsGet200ResponseTotalMin = 0

export const CollectionsGet200Response = zod.strictObject({
  coverImageUrl: zod.string().nullable(),
  description: zod.string().nullable(),
  id: zod.string(),
  items: zod.array(
    zod.strictObject({
      category: zod.strictObject({
        coverImageUrl: zod.string().nullable(),
        id: zod.string(),
        slug: zod.string(),
        title: zod.string(),
      }),
      counters: zod.strictObject({
        dzen: zod
          .number()
          .min(collectionsGet200ResponseItemsItemCountersDzenMin),
        instagram: zod
          .number()
          .min(collectionsGet200ResponseItemsItemCountersInstagramMin),
        telegram: zod
          .number()
          .min(collectionsGet200ResponseItemsItemCountersTelegramMin),
      }),
      coverImageUrl: zod.string().nullable(),
      id: zod.string(),
      slug: zod.string(),
      status: zod.enum(['active', 'hidden']),
      summary: zod.string(),
      tags: zod.array(zod.string()),
      title: zod.string(),
    }),
  ),
  page: zod.number().min(1),
  pageSize: zod.number().min(1),
  slug: zod.string(),
  title: zod.string(),
  total: zod.number().min(collectionsGet200ResponseTotalMin),
})

export const collectionsGet404ResponseStatusMin = 400
export const collectionsGet404ResponseStatusMax = 599

export const CollectionsGet404Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(collectionsGet404ResponseStatusMin)
    .max(collectionsGet404ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const collectionsGet422ResponseErrorsItemCodeRegExp = new RegExp(
  '^[a-z][a-z0-9_]*$',
)
export const collectionsGet422ResponseErrorsItemPointerRegExp = new RegExp(
  '^(?:|/(?:[^~/]|~0|~1)*)$',
)
export const collectionsGet422ResponseStatusMin = 400
export const collectionsGet422ResponseStatusMax = 599

export const CollectionsGet422Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  errors: zod.array(
    zod.strictObject({
      code: zod.string().regex(collectionsGet422ResponseErrorsItemCodeRegExp),
      detail: zod.string(),
      pointer: zod
        .string()
        .regex(collectionsGet422ResponseErrorsItemPointerRegExp),
    }),
  ),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(collectionsGet422ResponseStatusMin)
    .max(collectionsGet422ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const collectionsGet500ResponseStatusMin = 400
export const collectionsGet500ResponseStatusMax = 599

export const CollectionsGet500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(collectionsGet500ResponseStatusMin)
    .max(collectionsGet500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Public collection cover image.
 */
export const CollectionsGetPhotoParams = zod.strictObject({
  collectionSlug: zod.string(),
})

export const CollectionsGetPhoto200Response = zod.unknown()

export const collectionsGetPhoto404ResponseStatusMin = 400
export const collectionsGetPhoto404ResponseStatusMax = 599

export const CollectionsGetPhoto404Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(collectionsGetPhoto404ResponseStatusMin)
    .max(collectionsGetPhoto404ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const collectionsGetPhoto500ResponseStatusMin = 400
export const collectionsGetPhoto500ResponseStatusMax = 599

export const CollectionsGetPhoto500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(collectionsGetPhoto500ResponseStatusMin)
    .max(collectionsGetPhoto500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})
