/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Current principal favorite places.
 */

export const favoritesList200ResponseTotalMin = 0

export const FavoritesList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      category: zod.strictObject({
        coverImageUrl: zod.string().nullable(),
        id: zod.string(),
        slug: zod.string(),
        title: zod.string(),
      }),
      coverImageUrl: zod.string().nullable(),
      id: zod.string(),
      slug: zod.string(),
      status: zod.enum(['active', 'hidden']),
      summary: zod.string(),
      tags: zod.array(zod.string()),
      title: zod.string(),
    }),
  ),
  page: zod.number().min(1),
  pageSize: zod.number().min(1),
  total: zod.number().min(favoritesList200ResponseTotalMin),
})

export const favoritesList401ResponseStatusMin = 400
export const favoritesList401ResponseStatusMax = 599

export const FavoritesList401Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(favoritesList401ResponseStatusMin)
    .max(favoritesList401ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const favoritesList500ResponseStatusMin = 400
export const favoritesList500ResponseStatusMax = 599

export const FavoritesList500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(favoritesList500ResponseStatusMin)
    .max(favoritesList500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Place removed from favorites.
 */
export const FavoritesRemoveParams = zod.strictObject({
  placeId: zod.string(),
})

export const FavoritesRemove204Response = zod.void()

export const favoritesRemove401ResponseStatusMin = 400
export const favoritesRemove401ResponseStatusMax = 599

export const FavoritesRemove401Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(favoritesRemove401ResponseStatusMin)
    .max(favoritesRemove401ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const favoritesRemove403ResponseStatusMin = 400
export const favoritesRemove403ResponseStatusMax = 599

export const FavoritesRemove403Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(favoritesRemove403ResponseStatusMin)
    .max(favoritesRemove403ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const favoritesRemove500ResponseStatusMin = 400
export const favoritesRemove500ResponseStatusMax = 599

export const FavoritesRemove500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(favoritesRemove500ResponseStatusMin)
    .max(favoritesRemove500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Place added to favorites.
 */
export const FavoritesAddParams = zod.strictObject({
  placeId: zod.string(),
})

export const FavoritesAdd204Response = zod.void()

export const favoritesAdd401ResponseStatusMin = 400
export const favoritesAdd401ResponseStatusMax = 599

export const FavoritesAdd401Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(favoritesAdd401ResponseStatusMin)
    .max(favoritesAdd401ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const favoritesAdd403ResponseStatusMin = 400
export const favoritesAdd403ResponseStatusMax = 599

export const FavoritesAdd403Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(favoritesAdd403ResponseStatusMin)
    .max(favoritesAdd403ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const favoritesAdd404ResponseStatusMin = 400
export const favoritesAdd404ResponseStatusMax = 599

export const FavoritesAdd404Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(favoritesAdd404ResponseStatusMin)
    .max(favoritesAdd404ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const favoritesAdd500ResponseStatusMin = 400
export const favoritesAdd500ResponseStatusMax = 599

export const FavoritesAdd500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(favoritesAdd500ResponseStatusMin)
    .max(favoritesAdd500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})
