/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Check process liveness
 */
export const HealthLive200Response = zod.strictObject({
  status: zod.enum(['ok']),
})

export const healthLive500ResponseStatusMin = 400
export const healthLive500ResponseStatusMax = 599

export const HealthLive500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(healthLive500ResponseStatusMin)
    .max(healthLive500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Check bounded dependency readiness
 */
export const HealthReady200Response = zod.strictObject({
  checks: zod
    .record(zod.string(), zod.enum(['up', 'down', 'skipped']))
    .describe(
      'Extensible map of registered dependency names to their bounded check status.',
    ),
  status: zod.enum(['ok', 'unavailable']),
})

export const healthReady500ResponseStatusMin = 400
export const healthReady500ResponseStatusMax = 599

export const HealthReady500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(healthReady500ResponseStatusMin)
    .max(healthReady500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const HealthReady503Response = zod.strictObject({
  checks: zod
    .record(zod.string(), zod.enum(['up', 'down', 'skipped']))
    .describe(
      'Extensible map of registered dependency names to their bounded check status.',
    ),
  status: zod.enum(['ok', 'unavailable']),
})

/**
 * @summary Check the startup latch
 */
export const HealthStartup200Response = zod.strictObject({
  status: zod.enum(['ok', 'starting', 'unavailable']),
})

export const healthStartup500ResponseStatusMin = 400
export const healthStartup500ResponseStatusMax = 599

export const HealthStartup500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(healthStartup500ResponseStatusMin)
    .max(healthStartup500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const HealthStartup503Response = zod.strictObject({
  status: zod.enum(['ok', 'starting', 'unavailable']),
})
