/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Public category list.
 */
export const CategoriesList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      coverImageUrl: zod.string().nullable(),
      id: zod.string(),
      slug: zod.string(),
      title: zod.string(),
    }),
  ),
})

export const categoriesList500ResponseStatusMin = 400
export const categoriesList500ResponseStatusMax = 599

export const CategoriesList500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(categoriesList500ResponseStatusMin)
    .max(categoriesList500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Public category.
 */
export const CategoriesGetParams = zod.strictObject({
  categorySlug: zod.string(),
})

export const CategoriesGet200Response = zod.strictObject({
  coverImageUrl: zod.string().nullable(),
  id: zod.string(),
  slug: zod.string(),
  title: zod.string(),
})

export const categoriesGet404ResponseStatusMin = 400
export const categoriesGet404ResponseStatusMax = 599

export const CategoriesGet404Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(categoriesGet404ResponseStatusMin)
    .max(categoriesGet404ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const categoriesGet500ResponseStatusMin = 400
export const categoriesGet500ResponseStatusMax = 599

export const CategoriesGet500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(categoriesGet500ResponseStatusMin)
    .max(categoriesGet500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Category cover image.
 */
export const CategoriesGetPhotoParams = zod.strictObject({
  categorySlug: zod.string(),
})

export const CategoriesGetPhoto200Response = zod.unknown()

export const categoriesGetPhoto404ResponseStatusMin = 400
export const categoriesGetPhoto404ResponseStatusMax = 599

export const CategoriesGetPhoto404Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(categoriesGetPhoto404ResponseStatusMin)
    .max(categoriesGetPhoto404ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const categoriesGetPhoto500ResponseStatusMin = 400
export const categoriesGetPhoto500ResponseStatusMax = 599

export const CategoriesGetPhoto500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(categoriesGetPhoto500ResponseStatusMin)
    .max(categoriesGetPhoto500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})
