/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Administrative material library.
 */

export const adminMaterialsListQueryPageDefault = 1
export const adminMaterialsListQueryPageMax = 1000

export const adminMaterialsListQueryPageSizeDefault = 100
export const adminMaterialsListQueryPageSizeMax = 100

export const AdminMaterialsListQueryParams = zod.strictObject({
  platform: zod.enum(['dzen', 'telegram', 'instagram']).optional(),
  placeId: zod.string().min(1).optional(),
  adminStatus: zod
    .enum(['pending', 'approved', 'rejected', 'archived'])
    .optional(),
  linked: zod.boolean().optional(),
  page: zod
    .int()
    .min(1)
    .max(adminMaterialsListQueryPageMax)
    .default(adminMaterialsListQueryPageDefault),
  pageSize: zod
    .int()
    .min(1)
    .max(adminMaterialsListQueryPageSizeMax)
    .default(adminMaterialsListQueryPageSizeDefault),
})

export const adminMaterialsList200ResponseItemsItemDurationSecMin = 0

export const adminMaterialsList200ResponseTotalMin = 0

export const AdminMaterialsList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      adminStatus: zod.enum(['pending', 'approved', 'rejected', 'archived']),
      durationSec: zod
        .number()
        .min(adminMaterialsList200ResponseItemsItemDurationSecMin)
        .nullable(),
      excerpt: zod.string().nullable(),
      externalId: zod.string().nullable(),
      id: zod.string(),
      linked: zod.boolean(),
      mediaKind: zod.string().nullable(),
      mediaPreviewUrl: zod.url().nullable(),
      placeLink: zod.enum(['active', 'hidden']).nullable(),
      platform: zod.enum(['dzen', 'telegram', 'instagram']),
      publishedAt: zod.iso.date(),
      source: zod
        .strictObject({
          displayName: zod.string(),
          id: zod.string(),
          platform: zod.string(),
          url: zod.url(),
        })
        .nullable(),
      text: zod.string().nullable(),
      title: zod.string().nullable(),
      type: zod.enum(['post', 'reel', 'video']),
      url: zod.url(),
    }),
  ),
  page: zod.number().min(1),
  pageSize: zod.number().min(1),
  total: zod.number().min(adminMaterialsList200ResponseTotalMin),
})

export const adminMaterialsList401ResponseStatusMin = 400
export const adminMaterialsList401ResponseStatusMax = 599

export const AdminMaterialsList401Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsList401ResponseStatusMin)
    .max(adminMaterialsList401ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsList403ResponseStatusMin = 400
export const adminMaterialsList403ResponseStatusMax = 599

export const AdminMaterialsList403Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsList403ResponseStatusMin)
    .max(adminMaterialsList403ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsList404ResponseStatusMin = 400
export const adminMaterialsList404ResponseStatusMax = 599

export const AdminMaterialsList404Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsList404ResponseStatusMin)
    .max(adminMaterialsList404ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsList422ResponseErrorsItemCodeRegExp = new RegExp(
  '^[a-z][a-z0-9_]*$',
)
export const adminMaterialsList422ResponseErrorsItemPointerRegExp = new RegExp(
  '^(?:|/(?:[^~/]|~0|~1)*)$',
)
export const adminMaterialsList422ResponseStatusMin = 400
export const adminMaterialsList422ResponseStatusMax = 599

export const AdminMaterialsList422Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  errors: zod.array(
    zod.strictObject({
      code: zod
        .string()
        .regex(adminMaterialsList422ResponseErrorsItemCodeRegExp),
      detail: zod.string(),
      pointer: zod
        .string()
        .regex(adminMaterialsList422ResponseErrorsItemPointerRegExp),
    }),
  ),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsList422ResponseStatusMin)
    .max(adminMaterialsList422ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsList500ResponseStatusMin = 400
export const adminMaterialsList500ResponseStatusMax = 599

export const AdminMaterialsList500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsList500ResponseStatusMin)
    .max(adminMaterialsList500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Updated material.
 */
export const AdminMaterialsUpdateParams = zod.strictObject({
  materialId: zod.string(),
})

export const adminMaterialsUpdateBodyDurationSecMin = 0

export const AdminMaterialsUpdateBody = zod.strictObject({
  durationSec: zod.int().min(adminMaterialsUpdateBodyDurationSecMin).nullish(),
  platform: zod.enum(['dzen', 'telegram', 'instagram']).nullish(),
  publishedAt: zod.iso.date().optional(),
  title: zod.string().nullish(),
  type: zod.enum(['post', 'reel', 'video']).nullish(),
  url: zod.url().nullish(),
})

export const adminMaterialsUpdate200ResponseDurationSecMin = 0

export const AdminMaterialsUpdate200Response = zod.strictObject({
  durationSec: zod
    .number()
    .min(adminMaterialsUpdate200ResponseDurationSecMin)
    .nullable(),
  id: zod.string(),
  placeId: zod.string(),
  platform: zod.enum(['dzen', 'telegram', 'instagram']),
  publishedAt: zod.iso.date(),
  redirectUrl: zod.string().nullable(),
  title: zod.string().nullable(),
  type: zod.enum(['post', 'reel', 'video']),
  url: zod.url(),
})

export const adminMaterialsUpdate400ResponseStatusMin = 400
export const adminMaterialsUpdate400ResponseStatusMax = 599

export const AdminMaterialsUpdate400Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsUpdate400ResponseStatusMin)
    .max(adminMaterialsUpdate400ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsUpdate401ResponseStatusMin = 400
export const adminMaterialsUpdate401ResponseStatusMax = 599

export const AdminMaterialsUpdate401Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsUpdate401ResponseStatusMin)
    .max(adminMaterialsUpdate401ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsUpdate403ResponseStatusMin = 400
export const adminMaterialsUpdate403ResponseStatusMax = 599

export const AdminMaterialsUpdate403Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsUpdate403ResponseStatusMin)
    .max(adminMaterialsUpdate403ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsUpdate404ResponseStatusMin = 400
export const adminMaterialsUpdate404ResponseStatusMax = 599

export const AdminMaterialsUpdate404Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsUpdate404ResponseStatusMin)
    .max(adminMaterialsUpdate404ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsUpdate422ResponseErrorsItemCodeRegExp = new RegExp(
  '^[a-z][a-z0-9_]*$',
)
export const adminMaterialsUpdate422ResponseErrorsItemPointerRegExp =
  new RegExp('^(?:|/(?:[^~/]|~0|~1)*)$')
export const adminMaterialsUpdate422ResponseStatusMin = 400
export const adminMaterialsUpdate422ResponseStatusMax = 599

export const AdminMaterialsUpdate422Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  errors: zod.array(
    zod.strictObject({
      code: zod
        .string()
        .regex(adminMaterialsUpdate422ResponseErrorsItemCodeRegExp),
      detail: zod.string(),
      pointer: zod
        .string()
        .regex(adminMaterialsUpdate422ResponseErrorsItemPointerRegExp),
    }),
  ),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsUpdate422ResponseStatusMin)
    .max(adminMaterialsUpdate422ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsUpdate500ResponseStatusMin = 400
export const adminMaterialsUpdate500ResponseStatusMax = 599

export const AdminMaterialsUpdate500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsUpdate500ResponseStatusMin)
    .max(adminMaterialsUpdate500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

/**
 * @summary Material with updated review status.
 */
export const AdminMaterialsUpdateStatusParams = zod.strictObject({
  materialId: zod.string(),
})

export const AdminMaterialsUpdateStatusBody = zod.strictObject({
  adminStatus: zod.enum(['pending', 'approved', 'rejected', 'archived']),
})

export const adminMaterialsUpdateStatus200ResponseDurationSecMin = 0

export const AdminMaterialsUpdateStatus200Response = zod.strictObject({
  adminStatus: zod.enum(['pending', 'approved', 'rejected', 'archived']),
  durationSec: zod
    .number()
    .min(adminMaterialsUpdateStatus200ResponseDurationSecMin)
    .nullable(),
  excerpt: zod.string().nullable(),
  externalId: zod.string().nullable(),
  id: zod.string(),
  linked: zod.boolean(),
  mediaKind: zod.string().nullable(),
  mediaPreviewUrl: zod.url().nullable(),
  placeLink: zod.enum(['active', 'hidden']).nullable(),
  platform: zod.enum(['dzen', 'telegram', 'instagram']),
  publishedAt: zod.iso.date(),
  source: zod
    .strictObject({
      displayName: zod.string(),
      id: zod.string(),
      platform: zod.string(),
      url: zod.url(),
    })
    .nullable(),
  text: zod.string().nullable(),
  title: zod.string().nullable(),
  type: zod.enum(['post', 'reel', 'video']),
  url: zod.url(),
})

export const adminMaterialsUpdateStatus400ResponseStatusMin = 400
export const adminMaterialsUpdateStatus400ResponseStatusMax = 599

export const AdminMaterialsUpdateStatus400Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsUpdateStatus400ResponseStatusMin)
    .max(adminMaterialsUpdateStatus400ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsUpdateStatus401ResponseStatusMin = 400
export const adminMaterialsUpdateStatus401ResponseStatusMax = 599

export const AdminMaterialsUpdateStatus401Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsUpdateStatus401ResponseStatusMin)
    .max(adminMaterialsUpdateStatus401ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsUpdateStatus403ResponseStatusMin = 400
export const adminMaterialsUpdateStatus403ResponseStatusMax = 599

export const AdminMaterialsUpdateStatus403Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsUpdateStatus403ResponseStatusMin)
    .max(adminMaterialsUpdateStatus403ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsUpdateStatus404ResponseStatusMin = 400
export const adminMaterialsUpdateStatus404ResponseStatusMax = 599

export const AdminMaterialsUpdateStatus404Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsUpdateStatus404ResponseStatusMin)
    .max(adminMaterialsUpdateStatus404ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsUpdateStatus422ResponseErrorsItemCodeRegExp =
  new RegExp('^[a-z][a-z0-9_]*$')
export const adminMaterialsUpdateStatus422ResponseErrorsItemPointerRegExp =
  new RegExp('^(?:|/(?:[^~/]|~0|~1)*)$')
export const adminMaterialsUpdateStatus422ResponseStatusMin = 400
export const adminMaterialsUpdateStatus422ResponseStatusMax = 599

export const AdminMaterialsUpdateStatus422Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  errors: zod.array(
    zod.strictObject({
      code: zod
        .string()
        .regex(adminMaterialsUpdateStatus422ResponseErrorsItemCodeRegExp),
      detail: zod.string(),
      pointer: zod
        .string()
        .regex(adminMaterialsUpdateStatus422ResponseErrorsItemPointerRegExp),
    }),
  ),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsUpdateStatus422ResponseStatusMin)
    .max(adminMaterialsUpdateStatus422ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})

export const adminMaterialsUpdateStatus500ResponseStatusMin = 400
export const adminMaterialsUpdateStatus500ResponseStatusMax = 599

export const AdminMaterialsUpdateStatus500Response = zod.strictObject({
  code: zod.enum([
    'ACTIVE_IMPORT_EXISTS',
    'AUTHENTICATION_REQUIRED',
    'AUTHORIZATION_DENIED',
    'CATEGORY_IN_USE',
    'CATEGORY_NOT_FOUND',
    'CATEGORY_SLUG_CONFLICT',
    'COLLECTION_HAS_ACTIVE_IMPORT',
    'COLLECTION_MEMBERSHIP_CONFLICT',
    'COLLECTION_NOT_FOUND',
    'COLLECTION_PUBLISH_REQUIRES_ACTIVE_PLACE',
    'COLLECTION_REORDER_CONFLICT',
    'COLLECTION_SLUG_CONFLICT',
    'CONFLICT',
    'CONTENT_SOURCE_ALREADY_EXISTS',
    'CONTENT_SOURCE_IDENTITY_LOCKED',
    'CONTENT_SOURCE_NOT_FOUND',
    'DEPENDENCY_UNAVAILABLE',
    'FAVORITE_PLACE_NOT_FOUND',
    'IMPORT_CONTENT_SOURCE_NOT_FOUND',
    'IMPORT_RUN_NOT_FOUND',
    'INTERNAL_ERROR',
    'MALFORMED_REQUEST',
    'MATERIAL_NOT_FOUND',
    'MATERIAL_PLACE_NOT_FOUND',
    'NOT_FOUND',
    'PAYLOAD_TOO_LARGE',
    'PINNED_MATERIAL_NOT_FOUND',
    'PINNED_MATERIAL_NOT_LINKED',
    'PLACE_CATEGORY_NOT_FOUND',
    'PLACE_IMPORTS_UNAVAILABLE',
    'PLACE_IMPORT_ALREADY_ACTIVE',
    'PLACE_IMPORT_IDENTITY_CONFLICT',
    'PLACE_IMPORT_INPUT_INVALID',
    'PLACE_IMPORT_NOT_FOUND',
    'PLACE_IMPORT_PREVIEW_EXPIRED',
    'PLACE_IMPORT_PREVIEW_NOT_READY',
    'PLACE_IMPORT_VIEWER_UNAVAILABLE',
    'PLACE_MATERIAL_LINK_NOT_FOUND',
    'PLACE_NOT_FOUND',
    'PLACE_SLUG_CONFLICT',
    'RATE_LIMIT_EXCEEDED',
    'TELEGRAM_IMPORT_SOURCE_INVALID',
    'TELEGRAM_IMPORT_UNAVAILABLE',
    'UNSUPPORTED_MEDIA_TYPE',
    'VALIDATION_FAILED',
  ]),
  detail: zod.string(),
  instance: zod.string(),
  requestId: zod.string(),
  status: zod
    .number()
    .min(adminMaterialsUpdateStatus500ResponseStatusMin)
    .max(adminMaterialsUpdateStatus500ResponseStatusMax),
  title: zod.string(),
  type: zod.url(),
})
